version: '3'
services:
    dev-osticket:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: dev-osticket-image
        container_name: osticket
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
            MYSQL_HOST: 172.17.0.1
            MYSQL_USER: imis_admin
            MYSQL_PASSWORD: imis_admin
            MYSQL_DATABASE: ost_db
            INSTALL_CONFIG: /data/bin/imis-config.php
        ports:
            - '800:80'
        volumes:
            - type: bind
              source: /var/lib/docker/volumes/osticket-upload-volume/_data
              target: /data/upload/
            - type: bind
              source: /var/lib/docker/volumes/osticket-upload-volume/_data
              target: /var/log/nginx
