version: '3'
services:
    mysql:
        image: mysql:5
    osticket:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: osticket-image
        container_name: osticket
        environment:
            MYSQL_USER: imis_admin
            MYSQL_PASSWORD: imis_admin
            MYSQL_DATABASE: ost_db
            INSTALL_CONFIG: /data/bin/imis-config.php
        ports:
            - '800:80'
        volumes:
            - type: bind
              source: "/var/lib/docker/volumes/osticket-upload-volume/_data"
              target: "/data/upload/"
            - type: bind
              source: "/var/lib/docker/volumes/osticket-upload-volume/_data"
              target: "/var/log/nginx"
